name: uid_ovh
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  ndk: ^0.6.1-dev.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
